name = "BTH Forever"
author = "BTH Labs"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "713273d0950883b24649a04cb21a3b508e53c9aca3d26c85edae3b6abe7e8694"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
