name = "BTH Forever"
author = "BTH Labs"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39b44beedc67b08150d95238ea155be8e2d70de4f730f950e66c7303c265c7fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
