name = "BTH Forever"
author = "BTH Labs"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "000a7a93adf8f339b0dfa5ef844ed67cf8d08ae1c5b7ba52ead0f04cb31b6abe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
