name = "BTH Forever"
author = "BTH Labs"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05f06ba4b97594edf47c1a362d3d56f2f4bfba0be58522064bd4f57ab167e30b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
