name = "BTH Forever"
author = "BTH Labs"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0bd6b250ddb2bfd6af86266b4c41c4a1b57d7762a570cbcfae6258d870f8fcd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
