name = "BTH Forever"
author = "BTH Labs"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = ""

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
